version: '3.8'

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data: